framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    delay: 2000
                    max_retries: 3
                    multiplier: 2
                    max_delay: 0
            failed: 'doctrine://default?queue_name=failed'
        routing:
            'App\Events\Shared\AsyncMessageInterface': async

when@test:
    framework:
        messenger:
            transports:
                async: "in-memory://"
