framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    delay: 2000
                    max_retries: 3
                    multiplier: 2
                    max_delay: 0
            failed: 'doctrine://default?queue_name=failed_async_priority_medium'
            sync: 'sync://'
        routing:
            'App\Events\Shared\AsyncEventInterface': async
            'App\Events\Shared\SyncEventInterface': sync

when@test:
    framework:
        messenger:
            transports:
                async: "in-memory://"
